# -*- coding: utf-8 -*-
"""SentenceSimilarityProject.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goJO6TEjOBwW0NONrOVF90FRop8RBnP6
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

#Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Take input  from user
text1 = input("Enter Text 1:")
text2 = input("Enter Text 2")

#Convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

#Calcutate similarity
similarity = util.cos_sim(embedding1, embedding2)

#Show result
print("\nSimilarity Score:",round(float(similarity), 2))

if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")

!pip install transformers touch

#Load text generation model(GenAI)
generator = pipeline("text-generation",model="gpt2")

#Input prompt
prompt = "Artificial Intelligence in finance will"

#Generate text
result = generator(prompt,max_length = 50,num_return_sequences = 1)
print("AI Generator Text:")
print(result[0]['generated_text'])